### ISSUE TITLE
Feature: Email notifications

### ISSUE THREAD

**Issue by nemofang** [innocommerce/innoshop#1]
Currently after placing an order, there is no order confirmation email sent out. 

The platform should be able to send email notifications either with its own email server or 3rd party services such as SendGrid. The email notifications should include:
1. Order confirmation email to customer
2. New order notification email to store owner. (optional)
3. Shipping confirmation email to customers after order is shipped
4. Cancelation email to customer
5. Depends if the system will handle RMA: Return management related emails: notification email to store owner when customer request a return/exchange, reimbursement email to customer after return handled etc.

**Comment by yushine** [comment]
Thank you for your feedback and suggestions. We are delighted to inform you that the upcoming version of our platform will add email notifications to better serve both customers and store owners.

**Comment by yushine** [comment]
@nemofang  
The latest release, version 0.2.6, has added email notifications for new registrations, password recovery, new orders, and order updates.
