### ISSUE TITLE
Fatal error: Cannot redeclare front_route()

### ISSUE THREAD

**Issue by mddirga** [innocommerce/innoshop#50]
Dear all, how to solve this message? Tq

**Comment by yushine** [comment]
@mddirga Which page did it appear on? Can you take a screenshot?

**Comment by mddirga** [comment]
![Uploading innoshop.png…]()

**Comment by mddirga** [comment]
![innoshop](https://github.com/user-attachments/assets/25e3d7f3-17c5-45f8-ac2d-6fc6183a8b65)

**Comment by yushine** [comment]
<img width="996" alt="image" src="https://github.com/user-attachments/assets/4f70f1f7-f989-4db9-bc65-5e58d53e488d">
The version of the code I have seems different from yours. What version do you have? Did you clone it through git?

**Comment by yushine** [comment]
You can compare it with the current code on GitHub. @mddirga 

https://github.com/innocommerce/innoshop/blob/master/innopacks/common/helpers.php#L639
