### ISSUE TITLE
demo 后端密码改了？

### ISSUE THREAD

**Issue by gowy222** [innocommerce/innoshop#54]
https://demo.innoshop.cn/panel/login

Frontend: https://demo.innoshop.cn/
Backend: https://demo.innoshop.cn/panel
Account: [admin@innoshop.com](mailto:admin@innoshop.com)
Password: 123456 这个密码不对..还是用户名改了？
打算看一下后端具体功能的

**Comment by yushine** [comment]
@gowy222  可能被其他人修改了，我恢复一下吧。
