### ISSUE TITLE
有几个建议，订单状态，默认商品图片上传问题

### ISSUE THREAD

**Issue by gowy222** [innocommerce/innoshop#55]
1.订单状态，demo后台看了一下，状态种类有点少，也是很多开源框架的痛点, 期望丰富一点:
```
待支付（Pending）：订单已创建，等待客户完成支付。

支付处理中（Processing）：客户已发起支付，交易正在处理中。

支付成功（Successful）：支付已成功完成，商家已确认收到款项。

支付失败（Failed）：由于各种原因导致支付未能完成。

退款处理中（Refunding）：退款申请已被批准，正在处理退款。

已退款（Refunded）：退款已成功完成，包括全额退款和部分退款。

交易关闭（Closed）：交易已结束，可能是由于取消、退款完成或其他原因

```

2.编辑商品的时候，默认图片上传问题，按照常规使用习惯能不能区分选择:

```
上传到本地
上传到S3
远程url
```

期望越做越好

**Comment by yushine** [comment]
感谢您的反馈，我们非常重视您的建议。在进一步考虑您的建议之前，您可以通过使用插件来修改订单状态和流程。例如，如果您想要将订单状态从“pending”更改为“processing”，并且执行一些特定的操作，您可以按照以下代码示例进行操作：

```php
listen_hook_filter('service.state_machine.machines', function ($data) {
    $data['machines']['pending']['processing'][] = function () {
        // 在这里编写订单状态从 unpaid 变为 paid 时需要执行的逻辑
    };
    return $data;
});
```

这段代码通过监听钩子（hook）来过滤并修改状态机的配置。您可以在匿名函数中添加您希望在状态变更时执行的代码。

关于这段代码的具体原理和实现，您可以参考我们的GitHub仓库中的`StateMachineService.php`文件。以下是该文件的链接：

[StateMachineService.php](https://github.com/innocommerce/innoshop/blob/master/innopacks/common/src/Services/StateMachineService.php#L184)


另外，第二点的图片支持远程地址和对象存储(OSS), 我们会以插件的形式来支持。

**Comment by yushine** [comment]
> > 感谢您的反馈，我们非常重视您的建议。在进一步考虑您的建议之前，您可以通过使用插件来修改订单状态和流程。例如，如果您想要将订单状态从“pending”更改为“processing”，并且执行一些特定的操作，您可以按照以下代码示例进行操作：
> > ```
> > listen_hook_filter('service.state_machine.machines', function ($data) {
> >     $data['machines']['pending']['processing'][] = function () {
> >         // 在这里编写订单状态从 unpaid 变为 paid 时需要执行的逻辑
> >     };
> >     return $data;
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这段代码通过监听钩子（hook）来过滤并修改状态机的配置。您可以在匿名函数中添加您希望在状态变更时执行的代码。
> > 关于这段代码的具体原理和实现，您可以参考我们的GitHub仓库中的`StateMachineService.php`文件。以下是该文件的链接：
> > [StateMachineService.php](https://github.com/innocommerce/innoshop/blob/master/innopacks/common/src/Services/StateMachineService.php#L184)
> > 另外，第二点的图片支持远程地址和对象存储(OSS), 我们会以插件的形式来支持。
> 
> 收到，另外，官方能不能提供下docker部署的方案？dockerfile 还是docker部署简单靠谱, php环境隔离友好，不怕意外内部错误导致网店下线

Docker 部署方案正在路上
