### ISSUE TITLE
 substr(): Argument #1 ($string) must be of type string, null given

### ISSUE THREAD

**Issue by mprince2k18** [innocommerce/innoshop#61]
after execute composer install facing this

 substr(): Argument #1 ($string) must be of type string, null given

**Comment by yushine** [comment]
Can you please post a screenshot of the error when executing composer? @mprince2k18

**Comment by mprince2k18** [comment]
I just clone it from github repo and executed composer install.

**Comment by yushine** [comment]
> I just clone it from github repo and executed composer install.

Yes, I have clone it and run `composer install`, it works well. What's your php version?

![QQ_1728469471310](https://github.com/user-attachments/assets/ce9378f1-df40-4cd2-ae31-177d41921aae)
![QQ_1728469494718](https://github.com/user-attachments/assets/d4fd69f9-f42a-43d1-9071-41b55f9e294f)
