### ISSUE TITLE
能不能支持下 纯后端 admin的api JWT认证  往返json数据结构的产品接口, 主要用于第三方工具同步信息

### ISSUE THREAD

**Issue by gowy222** [innocommerce/innoshop#64]
这样方便对接第三方集成方平台和数据同步变更，而且有一些第三方支付集成平台也需要后置延迟独立回调api接口..

**Comment by yushine** [comment]
后端admin的api接口已经有了，不过不完善，比如产品相关和订单相关还没添加。后续会持续迭代完善。

相关代码: https://github.com/innocommerce/innoshop/blob/master/innopacks/restapi/routes/panel-api.php
文档地址: http://panel-api.innoshop.cn/

**Comment by yushine** [comment]
@gowy222  你是需要管理商品创建订单这些接口吗？ 我们这边调整下优先级下个版本加上。 当然，你也可以提交PR，我们审查后合并代码。
