### ISSUE TITLE
后台产品多属性SKU切换分组时值显示错误

### ISSUE THREAD

**Issue by xslong** [innocommerce/innoshop#78]
以演示的产品为例https://demo.innoshop.cn/panel/products/1/edit ，变体以Size分组显示时“Big / Blue”的价格是333（错误），网站前端显示价格是555（正确），其他的属性也错误。

多谢多谢

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/e3ae2c3d-4ab4-4efb-b136-d0f7385875c6">

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/d10c6909-da83-4114-bf00-8be4e1fb776c">

**Comment by GSGSDgggdzez** [comment]
Translation 
In eaglish
Taking the demo product as an example, when the variants are grouped by Size, the price for "Big / Blue" is 333 (incorrect), while the price displayed on the front end of the website is 555 (correct). Other attributes are also incorrect.

**Comment by yushine** [comment]
![image](https://github.com/user-attachments/assets/7817377d-f458-4e87-b50c-959d59c8b36e)
新版已经修复

**Comment by GSGSDgggdzez** [comment]
translation in english 
新版已经修复=The new version has been fixed
